apiVersion: v1
kind: Service
metadata:
  name: {{ include "meogle-ui.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "meogle-ui.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "meogle-ui.selectorLabels" . | nindent 4 }}
