apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "meogle-was.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "meogle-was.labels" . | nindent 4 }}
data:
  NODE_ENV: "prod"
  DB_HOST: {{ .Values.db.host | quote }}
  DB_PORT: {{ .Values.db.port | quote }}
  GITHUB_FRONTEND_REDIRECT_URL: {{ .Values.github.frontendRedirectUrl | quote }}
