apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  DB_DATABASE: {{ .Values.database.name | b64enc | quote }}
  DB_USERNAME: {{ .Values.database.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
