apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: meogle
spec:
  encryptedData:
    REDIS_PASSWORD: AgAl8CM5Ubk4ZfSY0QtgnJhA1LkwiK0GLrCFg7W/ytF80T1k+Im/v2mllGOFlnzvqi9MhybH9R57e2hPYck8Ilcs1OR2za4tBMlR+sFVRkN2qvMt9sIbghhjpMQ1ymt44j+gYjVz3AtS/BFMDH4PBDk++yXQys5eZ3QxpdJ2FgaNjZC0K+AWkQpr0Fn0fp9QM4w1aW7V1GfIcDfejZtF/jvJW1eRJj9bYHf6A59Hly6+pB7L97CSgpbpeVfG5IjENxe525FoAvLiLcsNrqsEwVf40u3zwFhb9NfarPIsxauq9hmf9RIh3V2tXm00PR6JlTKY/yZWFcH7b7iyXpe7Ckeg9SOF+nPz7noTaUFaqlfA2v1KqArZ3G0pkGhskLF0upg4yGCn87SE9C31aehr77MwoLECUAyR1Y00z2vhvg/JmxUr+k+98ygRLjCkB6DHWwvBgjDg0kJf3iJlDdDUqGRscUfnqDJ8FSJ869gGlCmzz9e9Wy5Ws5Wae9peXF+vKiM9o5kMdW4AstLPq5nSxKLzRPlhQDPe81Vvxsv57izcrYV6h3EE68oBIB0JZXo2fdtQHYNtRWcI1HoQ27S3oVLLgakhCPvlpxBRLr9TaS4GwkEVWrjSS/r4m/wO85z7pDp1HRG4YXsngYEA9o/uEnMURICPlAMv/tCqEewQAJE4dApFXnaoZVQ8zIzakJ0twiGEADFNgfVluTDToXMYbQ==
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: meogle
    type: Opaque