apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meogle-ingress
  namespace: argocd
spec:
  project: meogle-prod
  source:
    repoURL: https://github.com/meogle-share/blog-infra
    targetRevision: main
    path: apps/meogle-ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: meogle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
