apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meogle-was
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.meogle: "인프라"
    notifications.argoproj.io/subscribe.on-health-degraded.meogle: "인프라"
    notifications.argoproj.io/subscribe.on-sync-failed.meogle: "인프라"
    notifications.argoproj.io/subscribe.on-health-suspended.meogle: "인프라"
    notifications.argoproj.io/subscribe.on-health-missing.meogle: "인프라"
spec:
  project: meogle-prod
  source:
    repoURL: https://github.com/meogle-share/blog-infra
    targetRevision: main
    path: apps/meogle-was
  destination:
    server: https://kubernetes.default.svc
    namespace: meogle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
