apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    slack-webhook: AgCzN6RCTSnvvJcEKoM5swHwM7xi19KUVc2EjfGEGtxwo3L2o2UCThnq0LLGTieKuw8wx9Fvi+q0QUGQJ+8DZsNqwCM78deDwljweGOPfROykPfRil+WfYIyCU8Cn63cgfj+fHKH+N7jr6LC+Vza9CnzOC78vqm2dBeZmXccCUqhTs7tvw2YDsfYhTT07s1mtFjKxHdqXtQmUsKjd+CVMiI/GkkfIv3M635cxlJGsFs0LbkL7T59MGPXSNhliINneIP9B0MtJP/rHRsYt+GcaWNrb/kvEjF8otrhoSTsOx+R9nwbKyenyK5tC9WEnjR5EHSP63vatsOcXLUdeqLURWzHRCkozUCnMA7BBv/VfzfymLhm5mNQmKZDrehdwiPu2cz86rxtZyRK6KFSxz3lEwPxsOzg9NhWo3KF1EsTSMPK9ruUGMXriHh2DrbEth2o3mWT2jAH5ptL+2QRwfoPT5Arc1T9EFMAFTwJPg58PeiBGiISFKzfxzv7KBeZz5nqQq/dNOqtxcspWAYwkLWB1S/hQNL9Y8z9qiPyXGrUbocrh0IlrJlg61cl6/CerPmptq4AVZNuuLViI0o4y5D+WQ9avtWoG8IaFL/Ujzd/NuFH3QLYucbiOUGHWzz5STQzkyHSfEPhLZJqc/iXCE1O7Lhg3xatPNuHT+kuzKpYkMiTKBW1uXJbL+Dl0ytVvpc7kG0UA7Lbaeq/lGB3ZNN8Wy4XBcDQBOtgcR6bu8jIDQGKbxRdKiF+Ju+9gM9t89Juo43H8bhDx4y3dFxaAIF5eqvhASMWZ8Y3LWHRNMfpUK0hW6k=
  template:
    metadata:
      creationTimestamp: null
      name: argocd-notifications-secret
      namespace: argocd