apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    slack-token: AgBmS1/uUCQts7b3TugM5sFFQNC3K9Zfv1hvzDNPNVzeeuz/yarYNfiIvQbXy7f/kbM4MQy7TIFWHG/KxAF+DErSbniv6acFh0wiT+RCRCKQq26AQPbGj4xR+GOiYiBZoEVdbe2G3s6BdaCghhCIF9wFqeLiuqrESKoDBy/3HxctkJNRbeF8sckXKvQ5od0Ln/xhu4b/Zjb6/VQxQt4B9acE+IHI2EQUH0eWfA2fYzELdvkD8IKDBthfZITkJl63V8d05lXMAGRzEiBABXsGVkYvk5GUjsguHp/rFD48QkM6Vc3OdZxmg8W/e+uq3dvaaelgNC90KicxnU2MAWkymvh7GCBNmst4+YU6OJKQU33S0k8pDM9Buy/lgT2FQaDnYj0yp+uFnA7etHzWO8yXOK5rdySXXtuZBpF4vzy2PlrvtZad1aYI9uVxgKaP2Nxs0rge4pdmTxrtAHlheJ/UThmPDsUwxQjZjMS9erAbwIBb71BvjsFTL0mV7BHx84wtuS9UwuctvRnhXPHfy/BwugY+7MOgH12QsQSUA+m4geCELOOL524YdYeTfkqzT7JJHSivwMS6x8xpk1Me3wQw4FPr0zlJFkt/YflcqJS38H9RTEGWJtd8qR8l3Ra9pEEX8lA+5e/Yq080PnSV21akXbBGqknizDkNV05DFXARIbUuusku3SxYNQCtMacnuICMl9YFMCfhsxovB4LjNEm7WS8DjYPofvcb3x2vleXPZgDs7N3Io4DV/u6ax74PFUXRYJpkLwOoIXIGPWWWaA==
  template:
    metadata:
      creationTimestamp: null
      name: argocd-notifications-secret
      namespace: argocd